### ISSUE TITLE
Can't sharing the global scope between scripts in VSCode

### ISSUE THREAD

**Issue by dumpkeys** [BenoitZugmeyer/eslint-plugin-html#100]
eslint@5.2.0
![image](https://user-images.githubusercontent.com/41714405/43564966-7eba85b0-965b-11e8-910b-1bc27b06efe2.png)
add "sourceType": "script" change nothing

**Comment by BenoitZugmeyer** [comment]
I'm sorry but I can't reproduce. I tried this with the last version of vscode and its eslint extension. Please send more information, like the `eslint-plugin-html` version, your `.eslintrc` or maybe a gist with a small project so I can reproduce.

**Comment by Grawl** [comment]
just reproduced this with Twig

<img width="710" alt="image" src="https://user-images.githubusercontent.com/846774/48036280-52d6bb00-e1b3-11e8-80fc-19166db33d7c.png">

```
"eslint": "^5.8.0",
"eslint-plugin-html": "^4.0.6",
```

VSCode 1.28.2

[`vscode-eslint`](https://github.com/Microsoft/vscode-eslint) 1.7.0

user settings:

```
    "eslint.validate": [
        "javascript",
        "javascriptreact",
        "html",
        "twig"
    ]
```

Code sample:

```twig
<html class='no-site-js' lang='ru'>
	<head>
		<link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&amp;subset=cyrillic" rel="stylesheet">
		<script type='text/javascript'>
			const rootElement = document.getElementsByTagName('html')[0]
		</script>
		<script type='text/javascript'>
			window.rootElement = rootElement
			rootElement.classList.remove('no-site-js')
			rootElement.classList.add('site-js')
		</script>
		{% block head %}{% endblock %}
	</head>
</html>
```

**Comment by Grawl** [comment]
sample from `readme` causes this problem too

```html
<script>
var foo = 1;
</script>

<script>
alert(foo);
</script>
```
