### ISSUE TITLE
Plugin very slow in not particularly complex case

### ISSUE THREAD

**Issue by edg2s** [BenoitZugmeyer/eslint-plugin-html#102]
Linting this file with our current ruleset takes 12 seconds:

https://github.com/wikimedia/VisualEditor/blob/master/demos/ve/desktop.html

Larger JS files take fractions of a second.

**Comment by BenoitZugmeyer** [comment]
Thank you for pointing this out. This was because the file has a lot of script tags, and the plugin did run the whole ESLint process on every tags, even if they were empty. `eslint-plugin-html` now ignores script with `src` attributes, it should fix your issue.

**Comment by BenoitZugmeyer** [comment]
I published the fix in v4.0.6, cheers! :tada:

**Comment by edg2s** [comment]
Much better, thanks!
