### ISSUE TITLE
Unable to use with IntelliJ IDE

### ISSUE THREAD

**Issue by Grawl** [BenoitZugmeyer/eslint-plugin-html#106]
There is ESLint support in IntelliJ IDE but I cannot configure it to highlight errors and warnings into files in `twig` extension.

In built-in ESLint support, there is "Extra ESLint options" field in "Languages & Frameworks › JavaScript › Code Quality Tools › ESLint". I think it's CLI extra args field. I add `--ext='.twig'` here but with no effect.

There's also [`idok/eslint-plugin`](https://github.com/idok/eslint-plugin/issues/49) for IntelliJ IDEs.  There is "Extensions" field in "Other Settings › ESLint". I add `.twig` here but with no effect.

Related: https://github.com/idok/eslint-plugin/issues/49

**Comment by BenoitZugmeyer** [comment]
Try to run the same stuff *without* the `eslint-plugin-html`. Some editors are already doing this plugin job by removing the HTML parts from the files before feeding it to ESLint. Related to https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/47#issuecomment-279156204 Let me know if it works.
