### ISSUE TITLE
eslint --fix not work?

### ISSUE THREAD

**Issue by ptkdev** [BenoitZugmeyer/eslint-plugin-html#116]
## Description

I try auto-fix all indentation with `eslint --fix` but not work, esample:
`eslint  ./ --ext .html,.js,.php --cache --ignore-pattern .gitignore --fix`

## Setup configuration

* ESLint version: latest
* eslint-plugin-html version: latest
* NodeJS version: 10
* Operating System name and version: Windows 10
* ESLint configuration (.eslintrc): 
```json
{
	"env": {
		"browser": true,
		"es6": false,
		"node": false
	},
	"extends": "eslint:recommended",
	"parserOptions": {
		"sourceType": "module",
		"ecmaVersion": 2015
	},
	"plugins": [
		"html"
	],
	"settings": {
        "html/html-extensions": [".html", ".twig", ".vue", ".php"],
        "html/indent": "tab",
        "html/report-bad-indent": "warn"
	},
	"rules": {}
}
```

**Comment by BenoitZugmeyer** [comment]
What are the messages reported by ESLint? `Bad line indentation` messages are not (yet?) auto-fixable.

**Comment by BenoitZugmeyer** [comment]
@ptkdev are you planning to give me an answer or should I figure it out from the thumb down emoji?
