### ISSUE TITLE
Support Jinja template files

### ISSUE THREAD

**Issue by Stanzilla** [BenoitZugmeyer/eslint-plugin-html#124]
## Description

Currently when opening a html file that has jinja templates eslint falls over, because fails to find a doctype which does not exist in partials, would be lovely if this case could be supported.

## Alternatives

there is https://github.com/alexkuz/eslint-plugin-jinja/ but it is super outdated

**Comment by BenoitZugmeyer** [comment]
`eslint-plugin-html` does not care about doctype, so it must be something else. Is your partial have a valid html syntax? Did you read [the note about linting template files](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/master/README.md#linting-templates-or-php)?

**Comment by Stanzilla** [comment]
Oh hrm, that helps, thank you!
