### ISSUE TITLE
support multiple . in file extensions

### ISSUE THREAD

**Issue by vapier** [BenoitZugmeyer/eslint-plugin-html#127]
we use `.in` extensions to indicate a file is a partial input.  so if it has `.html.in`, it means we'll run some utility over it to produce the final `.html` file.

this setting does not work:
```js
  "html/html-extensions": [".html", ".html.in"]
```

instead, we need to list `.html` & `.in`.  but that means it now checks `.js.in` files too which we don't want.

can the extension test be expanded to support this ?

**Comment by BenoitZugmeyer** [comment]
Thank you for your suggestion, this has been added in v6.1.0!
