### ISSUE TITLE
Support for script tag with type text/babel

### ISSUE THREAD

**Issue by Ben52** [BenoitZugmeyer/eslint-plugin-html#13]
Hi! I would like to use this plugin to lint .vue files, however to get my IDE to recognize ES6, I have to specify `type="text/babel"` on my script tags, which prevents the linter from linting my javascript.

**Comment by BenoitZugmeyer** [comment]
No problem, I'll add this soon, or sooner if you send a PR !

**Comment by Ben52** [comment]
Done! #14

**Comment by BenoitZugmeyer** [comment]
Thank you!
