### ISSUE TITLE
Error when used with "plugin:@typescript-eslint/recommended-requiring-type-checking"

### ISSUE THREAD

**Issue by aress31** [BenoitZugmeyer/eslint-plugin-html#130]
## Description
It seems that using `eslint-plugin-html` together with `typescript-eslint` result in an error being thrown by `eslint` when running `eslint`.

Please see https://github.com/typescript-eslint/typescript-eslint/issues/2265 for the complete explanation.

**Comment by BenoitZugmeyer** [comment]
I don't reproduce your issue. I created a minimal project with the informations you sent on the linked issue and everything works as expected: https://gist.github.com/BenoitZugmeyer/9cc906084abd519ba8a8340925202a21#file-readme-md

Please add more information as requested by the [issue template](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/master/.github/ISSUE_TEMPLATE/bug-report.md).

**Comment by aress31** [comment]
This issue has gone away when upgrading my dependencies.
