### ISSUE TITLE
Can use it in the browser?

### ISSUE THREAD

**Issue by iliakan** [BenoitZugmeyer/eslint-plugin-html#132]
Hi,

I'm using ESLint in the browser.

Like this:

```js
import {Linter} from 'eslint/lib/linter/linter'; 
new Linter().verify(...code..., config, 'myfile.html');
```

Can I use eslint-plugin-html in the browser environment?

How do I attach it? I see node.js specific stuff, such as `require.resolve` in the sources.

**Comment by iliakan** [comment]
Looks like a rework is needed for that.

Maybe use `<template>` element for HTML "parsing".

**Comment by BenoitZugmeyer** [comment]
No, this can't be run in the browser. This plugin is hacking into node cache to patch ESLint functions. This can't work in the browser, I'm sorry.
