### ISSUE TITLE
Failed to load plugin 'html' declared in '.eslintrc.json': createRequire is not a function

### ISSUE THREAD

**Issue by windy-boy** [BenoitZugmeyer/eslint-plugin-html#133]
## 
When I use eslint-plugin-html, I have a problem.
Do you have the same problem as me? If so, please let us know the solution.

The warning message is as follows：
`WARNING in ./src/js/index.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load plugin 'html' declared in '.eslintrc.json': createRequire is not a function`

![image](https://user-images.githubusercontent.com/31606562/93576449-7d0f7b80-f9cd-11ea-9ffc-a043377c0f99.png)

**Comment by BenoitZugmeyer** [comment]
Please provide more information, as requested in [the bug report template](https://raw.githubusercontent.com/BenoitZugmeyer/eslint-plugin-html/master/.github/ISSUE_TEMPLATE/bug-report.md) you saw when opening the issue.
