### ISSUE TITLE
Problem with version

### ISSUE THREAD

**Issue by tasselchof** [BenoitZugmeyer/eslint-plugin-html#134]
## Description

 error  in ./src/main.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'html' declared in '.eslintrc.js': eslint-plugin-html error: It seems that eslint is not loaded.
If you think this is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

In the report, please include *all* those informations:

* ESLint version: 7.9.0
* ESLint path: /Users/tasselchof/PhpstormProjects/orderadmin-app/node_modules/eslint/lib/api.js
* Plugin version: 4.0.6

**Comment by BenoitZugmeyer** [comment]
Your plugin version is outdated, ESLint version 6+ is supported since eslint-plugin-html 6.0.0 https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/master/CHANGELOG.md . Please upgrade.
