### ISSUE TITLE
Error: Line number (14) greater than maximum line (13)

### ISSUE THREAD

**Issue by arturparkhisenko** [BenoitZugmeyer/eslint-plugin-html#16]
Comments and thoughts https://github.com/AtomLinter/linter-eslint/issues/359#issuecomment-174665358 and  https://github.com/AtomLinter/linter-eslint/issues/359#issuecomment-174873089
Updated gist by me with my example where i can reproduce it https://gist.github.com/arturparkhisenko/f9dd42e82a3713210076

**Comment by BenoitZugmeyer** [comment]
@arturparkhisenko can you test the `master` version of this plugin by installing it with `npm install git+https://github.com/BenoitZugmeyer/eslint-plugin-html` , and tell me if it fixes your issue?

**Comment by arturparkhisenko** [comment]
@BenoitZugmeyer tested with same example - no errors :+1: and after changing LF -> CRLF too. Thanks!
