### ISSUE TITLE
Twig handlebars result in parsing errors

### ISSUE THREAD

**Issue by pimhakkertgc** [BenoitZugmeyer/eslint-plugin-html#238]
## Description

When using Twig handles in the Javascript of a Twig file, ESLint's parser breaks.

Try using `{{ }}`, `{% %}`, or `{# #}` and the parser will not accept it. Is there a workaround?

## Setup configuration

- ESLint version: 8.33.0
- eslint-plugin-html version: 7.1.0
- NodeJS version: 16.15.0
- Operating System name and version: Windows 10 22621.1105
- ESLint configuration (.eslintrc): 

```
module.exports = {
  extends: [
    'eslint:recommended'
  ],
  plugins: [
    'html'
  ],
  settings: {
    "html/html-extensions": [".html", ".twig", ".html.twig"]
  },
  rules: {
    "no-undef": "off",
    "no-empty": "off",
    "no-unused-vars": "off"
  },
  parserOptions: {
    ecmaVersion: "latest"
  },
  env: {
    es6: true
  }
};
```

**Comment by BenoitZugmeyer** [comment]
See the README Troubleshooting section: https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-templates-or-php
