### ISSUE TITLE
How to ignore `<script>` without specified type?

### ISSUE THREAD

**Issue by aleen42** [BenoitZugmeyer/eslint-plugin-html#248]
## Description

Like `<script>` without specified type, how can we ignore to lint it?

## Alternatives

The plugin should ignore `text/javascript` when `html/javascript-mime-types` is set without it.

**Comment by BenoitZugmeyer** [comment]
> Like `<script>` without specified type, how can we ignore to lint it?

Currently you can't. Any reason to skip scripts whithout type attribute?

> The plugin should ignore `text/javascript` when `html/javascript-mime-types` is set without it.

This is already the case. If it solves your use-case, I suggest to favor this alternative.

**Comment by BenoitZugmeyer** [comment]
Thank you for your PR! I'll release it soon.
