### ISSUE TITLE
Flat config support

### ISSUE THREAD

**Issue by brettz9** [BenoitZugmeyer/eslint-plugin-html#250]
## Description

ESLint 8 began support for flat configs and ESLint 9 (currently in alpha) is moving to flat configs by default, so it would be great if eslint-plugin-html could support this mode:

Some docs:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

## Alternatives

Dropping support as of ESLint 9. :-(

**Comment by BenoitZugmeyer** [comment]
Thank you for the headsup, I'll look into it!

**Comment by BenoitZugmeyer** [comment]
I just released a new version with flat config support. Any feedback welcome!

**Comment by sebastianrothe** [comment]
Thanks. I'm having trouble on how to use it correctly with `eslint.config.js`.

As soon as I do `import eslintPluginHtml from "eslint-plugin-html";`, eslint won't lint js-Files anymore.

**Comment by BenoitZugmeyer** [comment]
@sebastianrothe see https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/262
