### ISSUE TITLE
Anybody have an example of a flat config file

### ISSUE THREAD

**Issue by toomanylogins** [BenoitZugmeyer/eslint-plugin-html#269]
## Description
I am new to eslint. I am trying to lint scripts in html. Clean install but confused about the eslint.config.mjs file. This is in flat format but examples here overleaf are different ? This is my config but lint not working for html.

`import globals from "globals";
import pluginJs from "@eslint/js";

export default [
  {languageOptions: { globals: globals.browser }},
  pluginJs.configs.recommended,

    {
        plugins: {
            html: {settings: {
    }}
        }
    }

];`

**Comment by patwork** [comment]
## example

eslint.config.cjs (CJS is more reliable than MJS, especially when used in GitHub Actions)
```javascript
const globals = require("globals");
const pluginJs = require("@eslint/js");
const html = require('eslint-plugin-html');

module.exports = [
	pluginJs.configs.recommended,
	{
		languageOptions: { globals: globals.browser },
	},
	{
		files: ['**/*.html'],
		plugins: { html },
	}
];
```

package.json
```json
{
  "devDependencies": {
    "@eslint/js": "^9.2.0",
    "eslint": "^9.2.0",
    "eslint-plugin-html": "^8.1.1",
    "globals": "^15.2.0"
  }
}
```

💀 example error.html
```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title>test</title>
	</head>
	<body>
		<p>begin</p>
		<script>
			function foo() {
				var a = bar;
				console.log(a);
			}
		</script>
		<p>end</p>
	</body>
</html>
```

💀 example error.js
```javascript
function foo() {
	var a = bar;
	console.log(a);
}
```

## results
/tmp/error.html
```
  10:13  error  'foo' is defined but never used  no-unused-vars
  11:13  error  'bar' is not defined             no-undef

/tmp/error.js
  1:10  error  'foo' is defined but never used  no-unused-vars
  2:10  error  'bar' is not defined             no-undef

✖ 4 problems (4 errors, 0 warnings)
```

**Comment by BenoitZugmeyer** [comment]
I updated all README examples to flatconfig / ESLint v9
