### ISSUE TITLE
Module build failed without reason

### ISSUE THREAD

**Issue by UranusCEO** [BenoitZugmeyer/eslint-plugin-html#27]
I am suffering a weird issue where module build failed without a reason. I tried to format my computer and make everything run again and i still get the same error but other computer run smoothly won't a problem.

Please help. Thanks

Attached Screenshot below:

![bug](https://cloud.githubusercontent.com/assets/5468792/17332051/ff15f410-58ff-11e6-96b4-8c15e9639d54.png)

**Comment by BenoitZugmeyer** [comment]
Thanks for reporting this issue. It seems it's related to the paths where your packages are installed:
```
E:\....\node_modules\.MODULE_NAME@VERSION\FILES.js
```
Instead of the conventional
```
E:\....\node_modules\MODULE_NAME\FILES.js
```
I'll fix your issue soon. Out of curiosity, do you know why your packages are installed like this?

**Comment by UranusCEO** [comment]
Thanks for knowing the issue.

I have no idea why it installed like that. It is a Window 10 Pro environment so maybe it cause the problem. 

But i really not sure why it will be like that. 

Waiting for your commit.

**Comment by BenoitZugmeyer** [comment]
Please let me know if it does the trick.
