### ISSUE TITLE
Include "espree" dependency in package.json

### ISSUE THREAD

**Issue by DEVTomatoCake** [BenoitZugmeyer/eslint-plugin-html#271]
[`espree`](https://www.npmjs.com/package/espree) is required by this package (at least when using the flat config, according to the file name), but not included as dependency directly. This can cause errors if `espree` is not installed from other packages already.
https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/9e91f974f5c19ec35169789facbc361d9ea41c5a/src/verifyWithFlatConfigPatch.js#L164

This issue apparently occurred after updating `eslint-plugin-html` to v53, and doesn't occur on v52. I'm unable to reproduce this locally, however as `espree` is directly used in this package it always should be included in the package.json.

**Comment by BenoitZugmeyer** [comment]
Thank you for the headsup. The goal was not to depend on espree directly, but use the default eslint parser to lint the JS files. It should be fixed on main, I'll do a release someday.

**Comment by BenoitZugmeyer** [comment]
It's released!
