### ISSUE TITLE
vue jsx no-unused-vars error

### ISSUE THREAD

**Issue by zyy7259** [BenoitZugmeyer/eslint-plugin-html#29]
When using [vue](https://github.com/vuejs/vue/tree/next) [jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx), Atom gives me many [no-unused-var](http://eslint.org/docs/rules/no-unused-vars) errors.

![image](https://cloud.githubusercontent.com/assets/2311742/17838020/eaef1652-67f4-11e6-84c1-af7dbf794dd3.png)

I don't know if it's ok to report this issue here, please help.

**Comment by BenoitZugmeyer** [comment]
This plugin lints JavaScript contained inside HTML files. It appears that vue jsx files are not HTML files. You should use [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react) with the rule [react/jsx-uses-vars](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md) to fix your issue.

**Comment by zyy7259** [comment]
thx~
