### ISSUE TITLE
Incompatibility issue between `eslint-plugin-html` and `@html-eslint`

### ISSUE THREAD

**Issue by m1rn** [BenoitZugmeyer/eslint-plugin-html#293]
## Description

According to the documentation, `eslint-plugin-html` should be compatible with `@html-eslint`. However, when I tried using both in my project, I noticed that `eslint-plugin-html` stops working. It seems like the issue is caused by `@html-eslint/parser`.

Here are the details:
- When I use `eslint-plugin-html` on its own, it works perfectly fine.
- As soon as I introduce `@html-eslint` and its parser, `eslint-plugin-html` no longer functions.

I’d like to know if this is a known issue or if there's any way to make these two plugins work together.

Thanks!

## Setup configuration

- ESLint version: 9.10.0
- eslint-plugin-html version: 8.1.1
- NodeJS version: 22.1.0
- Operating System name and version:
- ESLint configuration (.eslintrc/eslint.config.js):

```js
import html from "eslint-plugin-html"
import PARSER_HTML from '@html-eslint/parser'

export default [
  {
    files: ["**/*.html"],
    plugins: {
      html
    },
    languageOptions: {
      parser: PARSER_HTML
    },
    rules: {
      'no-console': 2
    }
  }
]
```

**Comment by BenoitZugmeyer** [comment]
You need both the `@html-eslint/parser` and `@html-eslint/eslint-plugin` to make it work. Ex:

```js
// one plugin to lint HTML inline scripts, the othe to lint HTML markup
import htmlScripts from "eslint-plugin-html"
import htmlMarkup from '@html-eslint/eslint-plugin'
import PARSER_HTML from '@html-eslint/parser'

export default [
  {
    files: ["**/*.html"],
    plugins: {
      htmlScripts,
      htmlMarkup,
    },
    languageOptions: {
      parser: PARSER_HTML
    },
    rules: {
      'no-console': 2
    }
  }
]
```
