### ISSUE TITLE
Server-side lintText usage and confirming (again) regarding browser usage

### ISSUE THREAD

**Issue by natoen** [BenoitZugmeyer/eslint-plugin-html#294]
Hello. I'm sorry for disturbing you.

I have seen issue [132](https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/132) but I want to confirm if we really don't have a chance to use this with [eslint-linter-browserify](https://github.com/UziTech/eslint-linter-browserify) for example.

I tried using [html-eslint](https://html-eslint.org/docs/getting-started) and [it works](https://github.com/yeonjuan/html-eslint/issues/192).

```javascript
const htmlEslint = require("@html-eslint/eslint-plugin");
const { Linter } = require( "eslint-linter-browserify");

const srcCode = `
<script type="text/javascript">
  var = 2;
</script>`

const linter = new Linter();
const lintMessages = linter.verify(srcCode, {
  ...htmlEslint.configs["flat/recommended"],
});
console.log(lintMessages);
```

eslint-plugin-html does not work on the other hand

```javascript
const html = require("eslint-plugin-html");
const { Linter } = require( "eslint-linter-browserify");

const srcCode = `
<script type="text/javascript">
  var a = ;
</script>`

const linter = new Linter();
const lintMessages = linter.verify(srcCode, {
  plugins: { html },
});
console.log(lintMessages);
```

[or even with lintText in the server](https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/2).

```javascript
const { ESLint } = require("eslint");
const html = require("eslint-plugin-html");

const srcCode = `
<script>
  var a = ;
</script>`;

(async function() {
    const eslint = new ESLint({
      plugins: { html } ,
  });

    const results = await eslint.lintText(srcCode);

    const formatter = await eslint.loadFormatter("stylish");
    const resultText = formatter.format(results);

    console.log(resultText);
})().catch((error) => {
    process.exitCode = 1;
    console.error(error);
});
```

I can understand the issue about the frontend but is this also true for not working in the server side (textLint of ESLint)? I would appreciate any help. Thank you very much. This library is awesome!

**Comment by BenoitZugmeyer** [comment]
### Re: browser support

`eslint-plugin-html` still relies on NodeJS module APIs to patch ESLint, so anything other than NodeJS isn't supported right now. That being said, I'll try to make a proper/cleaner plugin with the newly ESLint APIs one day, and it might work in the browser then.

### Re: server-side support

`eslint-plugin-html` only applies on files with an HTML-like extension ([see README](https://github.com/BenoitZugmeyer/eslint-plugin-html?tab=readme-ov-file#htmlhtml-extensions)). So you need to supply a file path ending with one of those extensions to `lintText`:

```js
  const results = await eslint.lintText(srcCode, { filePath: "test.html" });
```

It should work as expected.

**Comment by natoen** [comment]
Thank you very much! @BenoitZugmeyer
