### ISSUE TITLE
Error when parsing HTML file

### ISSUE THREAD

**Issue by jbe456** [BenoitZugmeyer/eslint-plugin-html#3]
When a HTML page starts like this:
```
<!DOCTYPE html>
<html>
<head>
```

The plugin throws the following error:
```
  1:2  error  Unexpected token !
```

**Comment by BenoitZugmeyer** [comment]
I'm sorry I can't reproduce.

Could you:
* make sure you added `"html"` in your eslintrc plugins entry
* tell me how you're using eslint? (via the command line or as a text editor plugin?)
* send me the result of `npm list`?

**Comment by BenoitZugmeyer** [comment]
Well, it's been almost two months. Feel free to reopen if you have more details.
