### ISSUE TITLE
Support .we extension

### ISSUE THREAD

**Issue by hanai** [BenoitZugmeyer/eslint-plugin-html#30]
`.we` and `.vue` are similar, and your plugin could interpret perfectly.

BTW: Perhaps this will be better to make `htmlExtensions` configurable.

**Comment by BenoitZugmeyer** [comment]
I'll add the .we extension next week (I'm on vacation right now).

For the `htmlExtensions` configurability: of course it would be better. It's not doable right now, see https://github.com/eslint/eslint/issues/3422 , but I may have found a way to make it happen by monkey-patching some ESLint internals... I'll give it a try.

**Comment by BenoitZugmeyer** [comment]
Extensions configuration will be available in the next, 2.0 release. Thank you for making me reconsider my previous ESLint monkey-patching method :+1:

**Comment by BenoitZugmeyer** [comment]
A take back my last comment.

**Comment by BenoitZugmeyer** [comment]
The `.we` extension will be supported in the next release, sadly a configurable extension list isn't going to happen right now.
