### ISSUE TITLE
Feature: custom file extensions

### ISSUE THREAD

**Issue by miljan-aleksic** [BenoitZugmeyer/eslint-plugin-html#4]
Hi!

there are files as [.vue](https://github.com/vuejs/vue-loader/blob/master/test/fixtures/basic.vue) that have a script inside which your plugin could interpret perfectly, but as far as I know the supported file extensions are limited. Is there any possibility to set custom file extensions?

**Comment by BenoitZugmeyer** [comment]
Hi, thanks for your feedback. Sadly, the eslint plugin system does not allow options. But I don't mind adding more file extensions. Let me know if that's ok for you.

**Comment by miljan-aleksic** [comment]
It does! Thanks :)

**Comment by miljan-aleksic** [comment]
BTW, the NPM is delivering the 1.0.0 version.

**Comment by BenoitZugmeyer** [comment]
Thanks, I published the latest version.

**Comment by cretueusebiu** [comment]
Can you add support for .php files too ?

**Comment by BenoitZugmeyer** [comment]
Did you test it? is linting php files with `<?php` tags works somewhat correctly?

**Comment by cretueusebiu** [comment]
@BenoitZugmeyer Yes, I've added the [php](https://github.com/BenoitZugmeyer/eslint-plugin-html/blob/master/src/index.js#L48) manually and it [works](http://i.imgur.com/6CzbCG7.png).

**Comment by BenoitZugmeyer** [comment]
Done, released

**Comment by cretueusebiu** [comment]
Great! Thanks.

**Comment by spencerhakim** [comment]
Can you add `.handlebars`?

**Comment by BenoitZugmeyer** [comment]
Sure, done. A release is planed this week-end.
