### ISSUE TITLE
Didn't do anything

### ISSUE THREAD

**Issue by rottmann** [BenoitZugmeyer/eslint-plugin-html#43]
What i am doing wrong?

node 6.4.0

package.json
```
{
  "name": "eslint-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "lint": "eslint src"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "eslint": "^3.12.2",
    "eslint-plugin-html": "^1.7.0"
  }
}
```

.eslintrc / .eslintrc.json
```
{
  "plugins": [
    "html"
  ],
  "settings": {
    "html/indent": "10",
    "html/report-bad-indent": 1
  }
}
```

src/test.vue
```
<script>
x = x
</script>
```

`$ npm run lint`

Result:
```
> eslint-test@1.0.0 lint /home/rottmann/test/eslint-test
> eslint src
```
No error, nothing else.

**Comment by BenoitZugmeyer** [comment]
When running eslint on a directory, it will lint only the `.js` files. You have to specify extra extensions to lint other file types: `eslint --ext .vue src`. See [documentation](http://eslint.org/docs/user-guide/command-line-interface#ext).

**Comment by rottmann** [comment]
Thanks! Did not see wood for the trees :evergreen_tree: :evergreen_tree: :evergreen_tree:

**Comment by martynchamberlin** [comment]
This helped immensely. I wonder if it'd be worthwhile adding this to this repo's README? I know that people _should_ know this but the fact is a lot of people don't. Me and my colleagues were stumped on this. :)

**Comment by rottmann** [comment]
It is not a plugin problem, it is a "user didn't read the eslint documentation"-Problem ;-) Shame on me.

**Comment by BenoitZugmeyer** [comment]
Sure, but it seems you're not alone, and adding a small paragraph in the README won't hurt anyone!
