### ISSUE TITLE
`no_unused_vars` triggered wrongly

### ISSUE THREAD

**Issue by jonathanGB** [BenoitZugmeyer/eslint-plugin-html#61]
Hi,

I have a file with the following structure, in which I get the following error:

> 'checkSubmit' is defined but never used

```html
<form onsubmit="return checkSubmit(1)">
  ...
</form>

<script>
  function checkSubmit(num) {
    ...
  }
</script>
```

Clearly, `checkSubmit` is used as a listener. Maybe the html is ignored by the plugin, even though it may have an impact on rules like this one.

Thanks!

**Comment by BenoitZugmeyer** [comment]
Hi, thanks for the report. Sadly, I have no idea how linting JS in HTML attributes could work... I can't think of a way to feed it to ESLint. I'm open to suggestions.

**Comment by hsxfjames** [comment]
How about parse onXXX attributes and transform into a fake JS segment? Then hack the messages from ESLint.

**Comment by armano2** [comment]
@BenoitZugmeyer after parsing html event attributes you will have to make rule thats triggers 
```js
context.markVariableAsUsed(name)
```

see https://eslint.org/docs/developer-guide/working-with-rules#the-context-object

**Comment by armano2** [comment]
@BenoitZugmeyer after parsing html event attributes you will have to make rule thats triggers 
```js
context.markVariableAsUsed(name)
```

see https://eslint.org/docs/developer-guide/working-with-rules#the-context-object

---------------

To parse attributes you have to use something like this

```js
  const parser = new htmlparser.Parser(
    {
...
      onattribute(name, value) {
        const cdata = []
        if (/^javascript:/i.test(value)) {
          const end = parser.endIndex - 1 // idk if quote is included
          chunks.push({
            type: "inlineScript",
            start: end - value.length + 10, // not sure about those values
            end,
            cdata,
          })
        } else if (/^on/i.test(name)) {
          const end = parser.endIndex - 1 // idk if quote is included
          chunks.push({
            type: "inlineScript",
            start: end - value.length,
            end,
            cdata,
          })
        }
      },
...
```

**Comment by BenoitZugmeyer** [comment]
Superseded by #123
