### ISSUE TITLE
may you add .jsp ?

### ISSUE THREAD

**Issue by biehu** [BenoitZugmeyer/eslint-plugin-html#67]
code:
<%-- --%>
error:
error  Parsing error: Unexpected token %

**Comment by BenoitZugmeyer** [comment]
I can't, in fact. There is no way to support template tags in JS code. For example:

```jsp
<script>
var foo = <%= bar %>;
</script>
```

To make sure that "bar" is a valid JS expression, we have to evaluate the JSP code. My advice is to cheat a little bit, like this:

```jsp
<script>
var foo;
// <%= "\nfoo = " + bar %>
</script>
```

Or if you want a comment

```jsp
<script>
// <%-- This is a comment --%>
</script>
```

(This is probably not valid JSP code, but I hope you get the idea)
