### ISSUE TITLE
Incompatability with eslint-plugin-eslint-comments

### ISSUE THREAD

**Issue by jscharett** [BenoitZugmeyer/eslint-plugin-html#70]
The eslint-plugin-eslint-comments plugin seems to have 2 rules that require the column of the reported failure to be -1.  This causes errors in this plugin as the TransformableString.locationToIndex checks for a 'valid' column of >= 0.  I raised the issue with that project, but it was deemed necessary to have a value of -1.  Is it possible to relax the rule here to allow for a negative value for column?

https://github.com/mysticatea/eslint-plugin-eslint-comments/issues/1

**Comment by BenoitZugmeyer** [comment]
Sorry for the reply delay. This is a smart hack from the `comments` plugin! I have a better fix idea: eslint is ignoring the messages before the `html` plugin is kicking in to remap messages, so we don't need to have invalid column numbers at this time. Let's just replace the column number with `1` in this case.
