### ISSUE TITLE
disable eslint in vue files whose script has property lang="ts"

### ISSUE THREAD

**Issue by vonweb** [BenoitZugmeyer/eslint-plugin-html#74]
can i disable eslint in vue files whose script has property lang="ts";
i know if i set type on script with value not match javascript-mime-types, i will be there, but is there any easier way? lang="ts" is already set

**Comment by BenoitZugmeyer** [comment]
No, it's not possible. The `lang` attribute has no meaning in HTML5, unlike the `type` attribute used to define how to interpret the content of the tag ([documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)). Like you suggested, if it is TypeScript code, you should set the `type` value to something else ([exemple](https://stackoverflow.com/a/13214026)].
