### ISSUE TITLE
removing first line break inside <script> tag

### ISSUE THREAD

**Issue by dperrymorrow** [BenoitZugmeyer/eslint-plugin-html#76]
when using with prettier, in `.vue` fiels the first line break is being removed from the script tag

```javascript
<script>
import moment from "moment-timezone";
import AssetBrowser from "./AssetBrowser.vue";

export default {
  name: "OfferSideBar",
  props: { offer: Object },
...
```

becomes: 

```javascript
<script>import moment from "moment-timezone";
import AssetBrowser from "./AssetBrowser.vue";
...
```

this is inside of Atom with the following settings...
```json
{
  "root": true,
  "parserOptions": {
    "ecmaVersion": 8
  },
  "plugins": [
    "prettier",
    "unicorn",
    "promise",
    "html"
  ],
...
```

**Comment by BenoitZugmeyer** [comment]
That's a good point. I will make a workaround for this issue. But for your information, it is advised to use the [vue plugin](https://github.com/vuejs/eslint-plugin-vue) for linting vue files.

**Comment by dperrymorrow** [comment]
cool thanks for looking into this.
