### ISSUE TITLE
Nothin is linted

### ISSUE THREAD

**Issue by Trolleule** [BenoitZugmeyer/eslint-plugin-html#78]
Hi,
Iam using EsLint v4.7 in Eclipse with tern and I wanted to test this plugin. My config looks like this:

`{
	"extends": "airbnb-base",
	"parserOptions": {
		"ecmaVersion": 6,
		"sourceType": "script",
		"ecmaFeatures": {
			"experimentalObjectRestSpread": true
		}
	},
    "plugins": ["html"],
	"rules": {
		"comma-dangle": 0
	}
}`

When i enable the plugin, nothing no of my html files are marked. Does it only work in cli?

**Comment by BenoitZugmeyer** [comment]
Hi ! No it doesn't work only on CLI, it is known to work in various editors (vim, Atom, Visual Code Studio...). My guess is that Eclipse invoke ESLint only when editing JS files, not HTML files. I will check this.

**Comment by BenoitZugmeyer** [comment]
Well, it seems to work out of the box, you don't need `eslint-plugin-html`. It looks like this is the same "isuse" as https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/47#issuecomment-279156204
