### ISSUE TITLE
dist-tags latest points to alpha version

### ISSUE THREAD

**Issue by oligot** [BenoitZugmeyer/eslint-plugin-html#79]
Hi,

I'm trying to update eslint-plugin-html by running

```
> yarn upgrade-interactive --latest
```

in one of my project. This gives

```
◯ eslint-plugin-html    latest  3.1.0   ❯  4.0.0-alpha.1
```

Running

```
> npm info eslint-plugin-html 'dist-tags'
```

gives

```js
{ latest: '4.0.0-alpha.1', next: '4.0.0-alpha.0' }
```

Shouldn't `latest` points to `3.2.2` and `next` to `4.0.0-alpha.1` ?

**Comment by BenoitZugmeyer** [comment]
Oh I forgot to specify a tag when publishing the latest alpha. Thank you very much, it should be fixed.

**Comment by oligot** [comment]
It is indeed fixed, thanks !
