### ISSUE TITLE
unable to run eslin on .js.erb files

### ISSUE THREAD

**Issue by sekmo** [BenoitZugmeyer/eslint-plugin-html#80]
Hi! I can't manage to make it work with .js.erb files... (eslint@4.9)
Here is my configuration:
```
{
  "extends": "airbnb",
  "rules": {
    "func-names": ["error", "never"],
    "no-var": 0,
    "vars-on-top": 0
  },
  "plugins": ["html"],
  "settings": {
    "html/html-extensions": [".erb", ".js.erb", ".js"],
  },
  "overrides": [
    {
      "files": ["app/**/*.js.erb", "app/**/*.js"]
    }
  ]
}
```

**Comment by BenoitZugmeyer** [comment]
Hi, what's the symptom? are they ignored, or is there an error message?

If you are runing eslint on a directory containing .erb files, please make sure to use the --ext option as stated [in the README](https://github.com/BenoitZugmeyer/eslint-plugin-html#usage):

```
eslint --ext .erb,.js src
```

Unrelated, but you shouldn't add the `.js` extension in `"html/html-extensions"` else it will break ESLint on JS files as it will considerate those files as HTML files.

**Comment by sekmo** [comment]
While it works when running `eslint --ext .js.erb,.js .`, the `.js.erb` files are ignored when running `eslint .`
There is no way to force the file extension in `.eslintrc`?
(I need to run `eslint` with no parameters)

**Comment by BenoitZugmeyer** [comment]
Sorry, there isn't. I saw you already find https://github.com/eslint/eslint/issues/7324 , and I'm pretty sure that ESLint:

* reads the .eslintrc files *after* listing files to lint, so it can't use it to resolve files to lint
* uses the `override` configuration entry by testing if the path of the file being linted matches the pattern, so you won't have any luck with this either

It's even stated in the [documentation](https://eslint.org/docs/user-guide/configuring#specifying-file-extensions-to-lint): "Currently the sole method for telling ESLint which file extensions to lint is by specifying a comma separated list of extensions using the --ext command line option".
