### ISSUE TITLE
no-undef rule triggered when function is defined in js file referenced by separate script tags src attribute

### ISSUE THREAD

**Issue by BlacKCaT27** [BenoitZugmeyer/eslint-plugin-html#81]
In my application, I have the following in my html:

        <script type="text/javascript" src="js/myJs.js"></script>
       
        <script>
            $(document).ready(function () {
                MyFunction();
            });
        </script>

MyFunction() is being flagged with the no-undef rule, even though it's defined and executes properly from within myJs.js. 

I'm also seeing "no-unused-vars" on that method in my js file, so perhaps this is just an issue in how either the html plugin or eslint itself is wired up. I'm assuming this case is normally handled correctly. Any thoughts on how to correct the problem on my end?

**Comment by BenoitZugmeyer** [comment]
Yes, neither eslint or this plugin are loading files declared as dependency. In your case, you should mark `MyFunction` as ["global"](https://eslint.org/docs/rules/no-undef#rule-details) in the script tag (as it is, in fact, a global), and ["exported"](https://eslint.org/docs/rules/no-unused-vars#exported) in `myJs.js`.
