### ISSUE TITLE
eslint 问题

### ISSUE THREAD

**Issue by jiangzhiguos** [BenoitZugmeyer/eslint-plugin-html#84]
为什么一直提示eslint，找不到路径啊？ 我全局都已经安装eslint了，并且在webstorm 上配置了。还是报这个错。
window系统
![qq 20171221161138](https://user-images.githubusercontent.com/26242617/34246478-c56ea4f2-e669-11e7-8033-5905648cfc55.jpg)
![qq 20171221161205](https://user-images.githubusercontent.com/26242617/34246479-c5ac9fbe-e669-11e7-9d88-2f3bfc0e90f5.png)

**Comment by BenoitZugmeyer** [comment]
See at the bottom of the README for hints about linting vue files https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-vue-files

If you need more help, please write in english (or french!) and provide your `.eslintrc`

**Comment by jiangzhiguos** [comment]
Why have you always prompted eslint, can't find the way? I have installed eslint all over the world and configured it on webstorm. This is the mistake.

window system
