### ISSUE TITLE
some wrong with the eslint-plugin-html in my webstorm

### ISSUE THREAD

**Issue by hilonliao** [BenoitZugmeyer/eslint-plugin-html#86]
(/Users/liaohailong/WebstormProjects/AudioReactNative/node_modules/eslint-plugin-html/src/index.js:65:11) at Object.  (/Users/liaohailong/WebstormProjects/AudioReactNative/node_modules/eslint-plugin-html/src/index.js:26:1) at Module._compile (module.js:635:30) at Object.Module._extensions..js (module.js:646:10) at Module.load (module.js:554:32) at tryModuleLoad (module.js:497:12) at Function.Module._load (module.js:489:3) at Module.require (module.js:579:17) at require (internal/module.js:11:18) at Object.load (/Users/liaohailong/WebstormProjects/AudioReactNative/node_modules/eslint/lib/config/plugins.js:129:26)

**Comment by hilonliao** [comment]
help~

**Comment by BenoitZugmeyer** [comment]
I can't do anything with this stack trace. Please send at least the actual error message.

**Comment by hilonliao** [comment]
![image](https://user-images.githubusercontent.com/5449597/35483691-14331274-0480-11e8-958d-b0a816651b5e.png)
When the previous error occurred, I repaired it with the prompt, and then there was a second error.

**Comment by nickensoul** [comment]
Maybe you should to try install eslint-plugin-html into eslint's directory (e.g., global or local).

**Comment by onlyone1221** [comment]
![image](https://user-images.githubusercontent.com/7358632/37271437-dfc33186-260d-11e8-9f06-9f73bb096cbe.png)

**Comment by BenoitZugmeyer** [comment]
Update the plugin to the latest version (v4.0.4) and if you still have the error, please add all requested informations to this issue.
