### ISSUE TITLE
does it not honor comment controls?

### ISSUE THREAD

**Issue by waffledonkey** [BenoitZugmeyer/eslint-plugin-html#88]
does`/* eslint-disable */`, `// eslint-disable-line` and `// eslint-disable-next-line` work?  how does one disable linting?

**Comment by BenoitZugmeyer** [comment]
Sure it does. Do you have any issue about it?

**Comment by waffledonkey** [comment]
The issue is that I had a <script> block with templating delimiters for variable interpolation.  var foo = {{ variable_from_context }}.  The }} is considered to be fatal and evaluation stopped long before any comment could be acted upon.  I solved the issue by giving that one script a different type attribute and then limiting which types the plugin should act upon.  

Cheers and thank you for your efforts.
