### ISSUE TITLE
eslint-plugin-html error

### ISSUE THREAD

**Issue by JTR354** [BenoitZugmeyer/eslint-plugin-html#90]
eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at 

"dependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.3",
    "babel-loader": "^7.1.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "clean-webpack-plugin": "^0.1.17",
    "eslint": "^3.19.0",
    "eslint-plugin-html": "^4.0.1",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "^2.30.1",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.5"
  },
  "devDependencies": {
    "eslint-plugin-babel": "^4.1.2"
  }

**Comment by pspgbhu** [comment]
i met the same iessue, this is my devDependencies in package.json

```
"devDependencies": {
    "babel-eslint": "^7.2.1",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-export-extensions": "^6.22.0",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "cross-env": "^5.1.3",
    "eslint": "^4.19.1",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-standard": "^7.1.0",
    "eslint-friendly-formatter": "^2.0.7",
    "eslint-plugin-html": "^2.0.1",
    "eslint-plugin-import": "^2.10.0",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^2.0.1",
    "wepy-compiler-babel": "^1.5.1",
    "wepy-compiler-less": "^1.3.10",
    "wepy-compiler-sass": "^1.3.12",
    "wepy-eslint": "^1.5.3"
  }
```

**Comment by pspgbhu** [comment]
@JTR354  

To set the version of  `eslint-plugin-import` to `^1.7.0` could fixed it temporarily.

**Comment by BenoitZugmeyer** [comment]
Is upgrading `eslint-plugin-html` to latest (4.0.2) an option?

**Comment by BenoitZugmeyer** [comment]
@JTR354 : eslint-plugin-html 4 is only compatible with ESLint 4.7+, so you need to update ESLint

We'll reopen the issue if you still have this problem after upgrading ESLint and the plugin.
