### ISSUE TITLE
ESlint in VScode WHAT'S WRONG?

### ISSUE THREAD

**Issue by Tonysmark** [BenoitZugmeyer/eslint-plugin-html#93]
-  I'm sure that I install eslint-plugin-html globally,then I got thoes errors
[Error - 16:26:16] ESLint stack trace:
[Error - 16:26:16] Error: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues
    at iterateESLintModules (e:\es6Learn\es6-webpack\node_modules\eslint-plugin-html\src\index.js:67:11)
    at Object.<anonymous> (e:\es6Learn\es6-webpack\node_modules\eslint-plugin-html\src\index.js:28:1)
    at Object.<anonymous> (e:\es6Learn\es6-webpack\node_modules\eslint-plugin-html\src\index.js:279:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
- And something like this
e:\es6Learn\es6-webpack\node_modules\eslint-config-mysticatea\base.js: Configuration for rule "indent" is invalid: Value "data["1"].flatTernaryExpressions" has additional properties. Referenced from: mysticatea Referenced from: E:\es6Learn\es6-webpack\package.json 
- I install eslint-config-mysticatea globally 
- FYI , I install eslint globally also,and the config file".eslintrc.json"  is down blow
```json 
{
    "env": {
        "browser": true,
        "commonjs": true,
        "es6": true
    },
    "extends": "eslint:recommended",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "rules": {
        "indent": [
            "error",
            "tab"
        ],
        "linebreak-style": [
            "error",
            "windows"
        ],
        "quotes": [
            "error",
            "single"
        ],
        "semi": [
            "error",
            "never"
        ],
        "no-var":[
            "error"
        ]
    }
}
```

- What am I missing?

**Comment by Zazck** [comment]
```powershell
npm uninstall eslint eslint-plugin-html
npm ln eslint@^4.19.1
npm ln eslint-plugin-html@^4.0.3
```

**Comment by lee-alderdice** [comment]
I am having this same issue.  I have checked npm outdated and run updates as needed and with the simplest package.json I can't get this working.

`{
    "extends": "standard",
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module"
    },
    "plugins": [
    "vue", "html"
    ],
    "env": {
        "browser": true,
        "node": true,
        "es6": true,
        "mocha": true
    }
}`

**Comment by BenoitZugmeyer** [comment]
I'm sorry but I can't reproduce your issue. Please provide a full stack trace with paths of the plugin and eslint.

Also, [you should not need the `html` plugin when using `vue`](https://github.com/BenoitZugmeyer/eslint-plugin-html#linting-vue-files): if you only lint .vue files, just remove the `html` plugin.

**Comment by Zazck** [comment]
@lee-alderdice 
I forgot how I figure this out, what I still remember is that problem may caused because you installed a wrong version eslint locally. problem solved after I execute that command in project folder
