### ISSUE TITLE
ESLint: eslint-plugin-html error:

### ISSUE THREAD

**Issue by xuchao321** [BenoitZugmeyer/eslint-plugin-html#95]
ESLint: eslint-plugin-html error: It seems that eslint is not loaded. If you think it is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues. Please see the 'ESLint' output channel for details.

**Comment by BenoitZugmeyer** [comment]
Please send additional details: what's your setup, your dependencies versions, etc.

**Comment by BenoitZugmeyer** [comment]
Update the plugin to the latest version (v4.0.4) and if you still have the error, please add all requested informations to this issue.
