### ISSUE TITLE
Error: eslint-plugin-html error: It seems that eslint is not loaded (VSCODE)

### ISSUE THREAD

**Issue by anpegar** [BenoitZugmeyer/eslint-plugin-html#98]
Hi, 
I've the same error and my plugin version is v4.0.4.
What happen? Do you need more info?

Thanks.

THE ERROR
----------------------------------------------------------------------------
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: eslint-plugin-html error: It seems that eslint is not loaded.
If you think this is a bug, please file a report at https://github.com/BenoitZugmeyer/eslint-plugin-html/issues

In the report, please include *all* those informations:

* ESLint version: 4.19.1
* ESLint path: C:\vs_workspace\eSga\node_modules\eslint\lib\api.js
* Plugin version: 4.0.4
* Plugin path: C:\vs_workspace\eSga\node_modules\eslint-plugin-html\src
* NodeJS version: v8.10.0
* Content of your lock file (package-lock.json or yarn.lock)
* How did you run ESLint (via the command line? an editor plugin?)
* The following stack trace:
    Error
    at iterateESLintModules (C:\vs_workspace\eSga\node_modules\eslint-plugin-html\src\index.js:94:7)
    at Object.<anonymous> (C:\vs_workspace\eSga\node_modules\eslint-plugin-html\src\index.js:27:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Plugins.load (C:\vs_workspace\eSga\node_modules\eslint\lib\config\plugins.js:101:26)

    at iterateESLintModules (C:\vs_workspace\eSga\node_modules\eslint-plugin-html\src\index.js:80:11)
    at Object.<anonymous> (C:\vs_workspace\eSga\node_modules\eslint-plugin-html\src\index.js:27:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Plugins.load (C:\vs_workspace\eSga\node_modules\eslint\lib\config\plugins.js:101:26)

 @ multi ./build/dev-client babel-polyfill ./src/main.js

**Comment by lukaszflorczak** [comment]
I confirm the problem

**Comment by howgoo** [comment]
I confirm the problem too.

**Comment by anpegar** [comment]
These are the rest of my devDependencies of my VUE + CORDOVA project.
Thanks.

"devDependencies": {
    "autoprefixer": "^8.6.3",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "chalk": "^2.4.1",
    "connect-history-api-fallback": "^1.5.0",
    "copy-webpack-plugin": "^4.5.1",
    "cpy-cli": "^2.0.0",
    "css-loader": "^0.28.11",
    "cssnano": "^3.10.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.18.0",
    "opn": "^5.3.0",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "ora": "^2.1.0",
    "rimraf": "^2.6.2",
    "semver": "^5.5.0",
    "shelljs": "^0.8.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "sw-precache-webpack-plugin": "^0.11.5",
    "uglify-es": "^3.3.10",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "vue-loader": "^15.2.4",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.12.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.3"
  },

**Comment by anpegar** [comment]
Hi again ... 
In order to continue working, I had to set this situation.

```
"devDependencies": {
    "autoprefixer": "^8.5.1",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "chalk": "^2.4.1",
    "connect-history-api-fallback": "^1.5.0",
    "copy-webpack-plugin": "^4.5.1",
    "cpy-cli": "^2.0.0",
    "css-loader": "^0.28.11",
    "cssnano": "^3.10.0",
    "eslint": "^4.19.1",
    "eslint-config-standard": "^11.0.0",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.12.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-promise": "^3.8.0",
    "eslint-plugin-standard": "^3.1.0",
    "eventsource-polyfill": "^0.9.6",
    "express": "^4.16.3",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "http-proxy-middleware": "^0.18.0",
    "opn": "^5.3.0",
    "optimize-css-assets-webpack-plugin": "^4.0.2",
    "ora": "^2.1.0",
    "rimraf": "^2.6.2",
    "semver": "^5.5.0",
    "shelljs": "^0.8.2",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.2",
    "sw-precache-webpack-plugin": "^0.11.5",
    "uglify-es": "^3.3.9",
    "uglifyjs-webpack-plugin": "^1.2.5",
    "url-loader": "^1.0.1",
    "vue-loader": "^14.2.2",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^4.10.2",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^2.1.4",
    "webpack-dev-middleware": "^3.1.3",
    "webpack-hot-middleware": "^2.22.2",
    "webpack-merge": "^4.1.2"
  },
```

**Comment by BenoitZugmeyer** [comment]
I broke everything in `v4.0.4`. It should be fine in `v4.0.5`. Really sorry for the inconvenience!

**Comment by anpegar** [comment]
ok, I confirm that all works fine.
Thanks a lot.
