### ISSUE TITLE
Prettier 1.13.x breaks eslint-plugin-html/eslint-plugin-prettier

### ISSUE THREAD

**Issue by nappy** [BenoitZugmeyer/eslint-plugin-html#99]
Upgrading prettier from ~1.12.1 to ^1.13.6 with eslint-plugin-prettier causes eslint-plugin-html to break.
Its probably a prettier issue, therefore you will find the full description there: https://github.com/prettier/prettier/issues/4759
I am not sure where this issue must be fixed, therefore I mention/crosspost it here.

**Comment by BenoitZugmeyer** [comment]
Thank you for reporting the issue. I guess you saw my comment [here](https://github.com/prettier/prettier/issues/4759#issuecomment-402854090). You can try to install the `@next` version and let me know if it solves your issue.

**Comment by BenoitZugmeyer** [comment]
The prettier plugin now have a nicer fix than the one I drafted!

See https://github.com/prettier/eslint-plugin-prettier/pull/111 . This has been released in `eslint-plugin-prettier` v2.7.0
